### ISSUE TITLE
CI jobs fails with latest changes

### ISSUE THREAD

**Issue by dirk-thomas** [ros-drivers/libuvc_ros#12]
The CI job http://jenkins.ros.org/job/devel-hydro-libuvc_ros/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/16/console fails since commit 30b3cfd1d20fef41f3a1077d3be3bcd3bb383d77.:

```
libuvc_ros/libuvc_camera/src/camera_driver.cpp:286:153: error: 'uvc_strerror' was not declared in this scope
```
